config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/about', to: 'welcome#about'
  get '/service', to: 'welcome#service'
  get '/contact', to: 'welcome#contact'
  post '/newcontact', to: 'welcome#newcontact'
  get '/career', to: 'welcome#career'
  get '/career/:id', to: 'welcome#get_career', as: 'to_apply'
  post '/jobpost/:id', to: 'welcome#applycareer'

  get '/admin', to: 'admin#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career.rb
class Career < ApplicationRecord
end

app/models/career_applied.rb
class CareerApplied < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'application'

  def index
  end

  def newcontact
    contact = Contact.new(
      name: params[:name],
      email: params[:email],
      phone: params[:phone],
      message: params[:message],
      contact_date: Date.today
    )
    if contact.save
      flash[:success] = 'Email sent successfully'
      redirect_to '/contact'
    end
  end

  def career
  	@careers = Career.all
  end

  def get_career
    @jobs = Career.all
    @job = Career.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def applycareer
  	newpost = CareerApplied.new(
      name: params[:name],
      email: params[:email],
      phone_no: params[:phone_no],
      resume_link: params[:resume_link],
      applied_for: params[:id],
      applied_date: Date.today
    )
    if newpost.save
      flash[:success] = 'Your application has been sent successfully'
      redirect_to '/career'
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="assets/favicon.png" />
    <title>Tablelabs Pvt Ltd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="assets/bootstrap.min.css">
    <link rel="stylesheet" href="assets/ready.css">
    <link rel="stylesheet" href="assets/demo.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <script type="text/javascript">
        toastr.<%= key %>('<%= value%>!', '<%= key.capitalize %>')
      </script>
    <% end %>
    <div class="wrapper">
      <div class="main-header">
        <div class="logo-header">
          <a href="/"><img src="assets/logo.png"></a>
          <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <button class="topbar-toggler more"><i class="fa fa-ellipsis-v"></i></button>
        </div>
        <nav class="navbar navbar-header navbar-expand-lg">
          <div class="container-fluid">
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
              <li class="nav-item dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false"> <img src="assets/profile.png" alt="user-img" width="36" class="img-circle"><span ><%= @current_name %></span></span> </a>
                <ul class="dropdown-menu dropdown-user">
                  <a class="dropdown-item" href="#"><i class="fa fa-user"></i>&emsp;My Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#"><i class="fa fa-power-off"></i>&emsp;Logout</a>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </div>
      <%= yield %>
    </div>
  </body>
  <script src="assets/ready.min.js"></script>
  <script src="assets/demo.js"></script>
  <script src="assets/jquery.3.2.1.min.js"></script>
  <script src="assets/popper.min.js"></script>
  <script src="assets/bootstrap.min.js"></script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="assets/favicon.png" />
    <title>Tablelabs Pvt Ltd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="assets/owl.carousel.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="assets/flexslider.css" type="text/css" media="all" />
    <link rel="stylesheet" href="assets/bootstrap.css">
    <link rel="stylesheet" href="assets/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">

    <script type="application/x-javascript">
      addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
        window.scrollTo(0, 1);
      }
    </script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <script type="text/javascript">
        toastr.<%= key %>('<%= value%>!', '<%= key.capitalize %>')
      </script>
    <% end %>
    <%= yield %>
    <script type="text/javascript" src="assets/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="assets/bootstrap.js"></script>
    <script src="assets/SmoothScroll.min.js"></script>
    <script type="text/javascript" src="assets/move-top.js"></script>
    <script type="text/javascript" src="assets/easing.js"></script>
    <script type="text/javascript">
      jQuery(document).ready(function($) {
        $(".scroll").click(function(event){   
          event.preventDefault();
          $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
        });
      });
    </script>
    <script type="text/javascript">
      $(document).ready(function() {
        $().UItoTop({ easingType: 'easeOutQuart' });
      });
    </script>

    <script defer src="assets/jquery.flexslider.js"></script>
    <script type="text/javascript">
      $(function(){
        SyntaxHighlighter.all();
          });
          $(window).load(function(){
          $('.flexslider').flexslider({
            animation: "slide",
            start: function(slider){
              $('body').removeClass('loading');
            }
        });
      });
    </script>

    <script src="assets/owl.carousel.js"></script>
  </body>
</html>

app/views/welcome/_get_career.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel"><%= @job.name %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>

			<div class="modal-body">
				<%= form_tag("/jobpost/#{@job.id}", method: "post", id:"newModal") do %>
					<div class="row career">
						<div class="col-md-12">
							<div class="form-group">
								<input type="text" name="name" placeholder="Name" required>
							</div>

							<div class="form-group">
								<input type="email" name="email" placeholder="Email" required>
							</div>

							<div class="form-group">
								<input type="text" name="phone_no" maxlength="10" onkeypress="check_numeric(this)" placeholder="Mobile Number" required>
							</div>

							<div class="form-group">
								<label><span style="color:#E25336;">Upload the Curriculum Vitae(PDF) on Dropbox/Google drive and then share the link.</span></label>
								<input type="text" name="resume_link" placeholder="https://" required>
							</div>

							<div class="form-group">
								<select name="applied_for" disabled="true" required>
									<option value="<%= @job.id %>"><%= @job.name %></option>
								</select>
							</div>
						</div>

						<div class="col-md-12">
							<div class="col-md-2 pull-right">
								<input type="submit" name="submit" value="Apply">
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
<head></head>

<body>
	<!-- Header Start -->
	<header>
		<div class="container-fluid agile-banner_nav">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href="/"><img src="assets/logo.png"></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item"><a class="nav-link" href="/">Home</a></li>
						<li class="nav-item active"><a class="nav-link" href="/about">About</a></li>
						<li class="nav-item"><a class="nav-link" href="/service">Services</a></li>
						<li class="nav-item"><a class="nav-link" href="/contact">Contact Us</a></li>
					</ul>
				</div>
			</nav>
		</div>
	</header>
	<!-- Header End -->

	<!-- inner page banner-->
	<div class="inner-banner"></div>
	<!-- //inner page banner-->

	<!-- About us -->
	<section class="about py-5 my-lg-5">
		<div class="container">
			<h3 class="heading text-center text-capitalize mb-5">What makes us different</h3>
			<div class="spldishes-agileinfo">
				<div class="spldishes-grids">
					<!-- Owl-Carousel -->
					<div id="owl-demo" class="owl-carousel agileinfo-gallery-row">
						<div class="item g1">
							<img class="lazyOwl" src="assets/slide1.jpg" alt=""/>
							<h4 class="mt-4 text-uppercase">Design Planning</h4>
							<p class="my-2">Planning and managing digital content to meet the needs the public</p>
							<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
						</div>
						<div class="item g1">
							<img class="lazyOwl" src="assets/slide2.jpg" alt=""/>
							<h4 class="mt-4 text-uppercase">Business Meeting</h4>
							<p class="my-2">Once that goal is established, prioritize the list of topics from most important to least</p>
							<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
						</div>
						<div class="item g1">
							<img class="lazyOwl" src="assets/slide3.jpg" alt=""/>
							<h4 class="mt-4 text-uppercase">Programming</h4>
							<p class="my-2">Build and execute monthly programming plans for the service; promoting & featuring</p>
							<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
						</div>
						<div class="item g1">
							<img class="lazyOwl" src="assets/slide4.jpg" alt=""/>
							<h4 class="mt-4 text-uppercase">Confidence Skills</h4>
							<p class="my-2">Positive thinking, practice, training, knowledge and talking to other people</p>
							<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
						</div>
						<div class="item g1">
							<img class="lazyOwl" src="assets/slide5.jpg" alt=""/>
							<h4 class="mt-4 text-uppercase">Beauty design</h4>
							<p class="my-2">Designing a good website that accommodates a lot of content</p>
							<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
						</div> 
						<div class="item g1">
							<img class="lazyOwl" src="assets/slide6.jpg" alt=""/>
							<h4 class="mt-4 text-uppercase">Creative thinking</h4>
							<p class="my-2">Looking at something in a new way. It is the very definition of “thinking outside the box.”</p>
							<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
						</div>
					</div> 
				</div>  
				<div class="clearfix"> </div>
			</div>
		</div>
	</section>
	<!-- //About us -->

	<!-- help -->
	<section class="help">
		<div class="layer py-5">
			<div class="container py-lg-5">
			<h3 class="heading text-center text-capitalize mb-5">We help you in </h3>
				<div class="row help_grids">
					<div class="col-sm-4">
						<div class="row">
							<div class="col-lg-3 mb-lg-0 mb-4 icon">
								<i class="fas fa fa-briefcase"></i>
							</div>
							<div class="col-lg-9">
								<h4 class="text-uppercase mb-3">Business</h4>
								<p class="mb-3">10 to 20 keywords analyzed and optimized. Quality backlinks from relevant sources & regular quality content generation</p>
								<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
							</div>
						</div>
					</div>
					<div class="col-sm-4 mt-sm-0 mt-4">
						<div class="row">
							<div class="col-lg-3 mb-lg-0 mb-4 icon">
								<i class="fas fa fa-signal"></i>
							</div>
							<div class="col-lg-9">
								<h4 class="text-uppercase mb-3">Strategy</h4>
								<p class="mb-3">Our on-site team of experts uses ethical and intelligent SEO techniques to help you get on top and stay on top</p>
								<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
							</div>
						</div>
					</div>
					<div class="col-sm-4 mt-sm-0 mt-4">
						<div class="row">
							<div class="col-lg-3 mb-lg-0 mb-4 icon">
								<i class="fab fa fa-connectdevelop"></i>
							</div>
							<div class="col-lg-9">
								<h4 class="text-uppercase mb-3">Technology</h4>
								<p class="mb-3">Manual submission of site to relevant niche directories. Local business directory and social bookmarking submissions</p>
								<a href="#">Read More <i class="fas fa fa-angle-right"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- //help -->

	<!-- about top -->
	<section class="about-top py-5 my-lg-5">
		<div class="container">
			<h3 class="heading text-center text-capitalize mb-5">Checkout file Project </h3>
			<div class="row top-grids">
				<div class="col-lg-4">
					<h4 class="mb-4 text-capitalize">We offer a wide variety of data entry services. Our data entry services include</h4>
					<a href="#">Download file <i class="fas fa fa-download"></i></a>
				</div>
				<div class="col-lg-6 my-lg-0 my-6">
					<p>Everyone at Data Entry India is proud to be associated with a unique approach to data entry that keeps our clients happy. We then set out to deliver the highest levels of data quality and data accuracy with an expeditious turnaround. We offer output in various formats such as Text (.txt), Microsoft Word (.doc), Microsoft Excel (.xls), Microsoft Access (.mdb), and Microsoft Access Portable Document (.pdf) formats. The output can be delivered via E-mail, FTP upload or CD-R or CD-W.</p>
				</div>
				<div class="col-lg-3 col-sm-6">
					<img src="images/slide1.jpg" alt="" class="img-fluid">
				</div>
			</div>
		</div>
	</section>
	<!-- //about top -->

	<!-- project -->
	<section class="project py-5 text-center">
		<div class="container">
			<h3 class="text-capitalize mb-5">Do you want to start a new project ?</h3>
			<a href="/contact" class="text-uppercase"><i class="fas fa fa-envelope-open"></i> contact us </a>
		</div>
	</section>
	<!-- //project -->

	<!-- footer -->	
	<footer>
		<div class="container py-5">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<h3 class="text-uppercase mb-3">Address</h3>
					<address>
						<p><strong>Tablelabs OPC Private Limited</strong></p>
						<p class="mb-3">#171, Ganapathy Nagar, Thiruvanaikoil, Trichy - 620005 Tamil Nadu, India.</p>
						<p><strong>Phone</strong> : +91 74028 11006</p>
						<p><strong>Email</strong> : <a href="mailto:tablelab4@yahoo.com">tablelab4@yahoo.com</a></p>
					</address>
				</div>
				<div class="col-lg-2 col-md-6 mt-lg-0 mt-sm-0 mt-4 p-md-0">
					<h3 class="text-uppercase mb-3">links</h3>
					<div class="links">
						<a class="pt-2 text-capitalize" href="/"><i class="fas fa fa-angle-right"></i> Home</a>
						<a class="pt-2 text-capitalize" href="/about"><i class="fas fa fa-angle-right"></i> About</a>
						<a class="pt-2 text-capitalize" href="/career"><i class="fas fa fa-angle-right"></i> Career</a>
						<a class="pt-2 text-capitalize" href="/service"><i class="fas fa fa-angle-right"></i> Services</a>
						<a class="pt-2 text-capitalize" href="/contact"><i class="fas fa fa-angle-right"></i> Contact Us</a>
					</div>	
				</div>
				<div class="col-lg-3 col-md-6 mt-lg-0 mt-4">
					<h3 class="text-uppercase mb-3">Recent posts</h3>
					<div class="posts">
						<p class="pt-2">Automated set-ups
						<span class="font-italic">31st Dec, 2017.</span></p>
						<p class="py-2 my-2 middle">Impressive processing speed
						<span class="font-italic">31st Jan, 2018.</span></p>
						<p class="pt-2">Highly scalable software
						<span class="font-italic">31st Feb, 2018.</span></p>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 mt-lg-0 mt-4">
					<h3 class="text-uppercase mb-3">Newsletter</h3>
					<p class="mb-4 pt-2">Subscribe to Our Newsletter to get Important News, Amazing Offers & More</p>
					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter your email..." required="">
						<button class="btn1"><i class="far fa fa-envelope-o"></i></button>
						<div class="clearfix"> </div>
					</form>
				</div>
			</div>
		</div>
	</footer>
	<!-- footer -->


	<!-- copyright -->
	<div class="copyright py-4">
		<div class="container">
			<div class="copyrightgrids row">
				<div class="col-lg-6 col-12">
					<p>© 2018 <span>Table Labs</span>. All Rights Reserved</p>
				</div>
				<div class="col-lg-6 col-12">
					<ul class="social text-right mt-lg-0 mt-3">
						<li><p class="mx-2 text-capitalize">follow us on : </p></li>
						<li class="mx-2"><a href="#" class="socialfb"><span class="fab fa fa-facebook-f"></span></a></li>
						<li class="mx-2"><a href="#" class="socialtw"><span class="fab fa fa-twitter"></span></a></li>
						<li class="mx-2"><a href="#" class="socialgp"><span class="fab fa fa-google-plus"></span></a></li>
						<li class="mx-2"><a href="#" class="socialln"><span class="fab fa fa-linkedin"></span></a></li>
						<li class="mx-2"><a href="#" class="socialyh"><span class="fab fa fa-yahoo"></span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- //copyright -->
</body>
<script>
	$(document).ready(function() {
		$("#owl-demo").owlCarousel ({
			items : 3,
			lazyLoad : true,
			autoPlay : true,
			pagination : true,
		});
	});
</script>
</html>

app/views/welcome/career.html.erb
<!DOCTYPE html>
<html>
<head></head>

<body>
	<!-- Header Start -->
	<header>
		<div class="container-fluid agile-banner_nav">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href="/"><img src="assets/logo.png"></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item"><a class="nav-link" href="/">Home</a></li>
						<li class="nav-item"><a class="nav-link" href="/about">About</a></li>
						<li class="nav-item"><a class="nav-link" href="/service">Services</a></li>
						<li class="nav-item active"><a class="nav-link" href="/contact">Contact Us</a></li>
					</ul>
				</div>
			</nav>
		</div>
	</header>
	<!-- Header End -->

	<!-- inner page banner-->
	<div class="inner-banner"></div>
	<!-- //inner page banner-->

	<section class="contact py-5 my-lg-5">
		<div class="container">
			<h3 class="heading text-center text-capitalize mb-5">join with us</h3>
			<div class="row contact_information">
				<p>We are looking for those passionate about innovating, open source technologies, and disrupting pre-existing paradigms, in a place where collaboration, intellectual challenge, and fun are paramount.</p>

				<div class="job-content">
					<div class="tab">
						<% for c in @careers %>
							<button class="tablinks" onclick="openCity(event, '<%= c.id %>')" id="defaultOpen"><%= c.name %></button>
						<% end %>
					</div>

					<% for co in @careers %>
						<div id="<%= co.id %>" class="tabcontent">
							<h3><%= co.name %></h3>
							<h5>Job Description</h5>
							<p><%= co.description%></p>
							<h5>Skills</h5>
							<p>
								<ul>
									<% co.skills.split('@').each do |s| %>
										<% if !s.empty? %>
											<li><%= s %></li>
										<% end %>
									<% end %>
								</ul>
							</p>
							<a href="<%= to_apply_path(co.id)%>" class="applybtn" data-remote="true">Apply&emsp;<i class="fa fa-arrow-down"></i></a>							
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</section>

	<!-- project -->
	<section class="project py-5 text-center">
		<div class="container">
			<h3 class="text-capitalize mb-5">Do you want to start a new project ?</h3>
			<a href="/contact" class="text-uppercase"><i class="fas fa fa-envelope-open"></i> contact us </a>
		</div>
	</section>
	<!-- //project -->

	<!-- footer -->	
	<footer>
		<div class="container py-5">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<h3 class="text-uppercase mb-3">Address</h3>
					<address>
						<p><strong>Tablelabs OPC Private Limited</strong></p>
						<p class="mb-3">#171, Ganapathy Nagar, Thiruvanaikoil, Trichy - 620005 Tamil Nadu, India.</p>
						<p><strong>Phone</strong> : +91 74028 11006</p>
						<p><strong>Email</strong> : <a href="mailto:tablelab4@yahoo.com">tablelab4@yahoo.com</a></p>
					</address>
				</div>
				<div class="col-lg-2 col-md-6 mt-lg-0 mt-sm-0 mt-4 p-md-0">
					<h3 class="text-uppercase mb-3">links</h3>
					<div class="links">
						<a class="pt-2 text-capitalize" href="/"><i class="fas fa fa-angle-right"></i> Home</a>
						<a class="pt-2 text-capitalize" href="/about"><i class="fas fa fa-angle-right"></i> About</a>
						<a class="pt-2 text-capitalize" href="/career"><i class="fas fa fa-angle-right"></i> Career</a>
						<a class="pt-2 text-capitalize" href="/service"><i class="fas fa fa-angle-right"></i> Services</a>
						<a class="pt-2 text-capitalize" href="/contact"><i class="fas fa fa-angle-right"></i> Contact Us</a>
					</div>	
				</div>
				<div class="col-lg-3 col-md-6 mt-lg-0 mt-4">
					<h3 class="text-uppercase mb-3">Recent posts</h3>
					<div class="posts">
						<p class="pt-2">Automated set-ups
						<span class="font-italic">31st Dec, 2017.</span></p>
						<p class="py-2 my-2 middle">Impressive processing speed
						<span class="font-italic">31st Jan, 2018.</span></p>
						<p class="pt-2">Highly scalable software
						<span class="font-italic">31st Feb, 2018.</span></p>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 mt-lg-0 mt-4">
					<h3 class="text-uppercase mb-3">Newsletter</h3>
					<p class="mb-4 pt-2">Subscribe to Our Newsletter to get Important News, Amazing Offers & More</p>
					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter your email..." required="">
						<button class="btn1"><i class="far fa fa-envelope-o"></i></button>
						<div class="clearfix"> </div>
					</form>
				</div>
			</div>
		</div>
	</footer>
	<!-- footer -->


	<!-- copyright -->
	<div class="copyright py-4">
		<div class="container">
			<div class="copyrightgrids row">
				<div class="col-lg-6 col-12">
					<p>© 2018 <span>Table Labs</span>. All Rights Reserved</p>
				</div>
				<div class="col-lg-6 col-12">
					<ul class="social text-right mt-lg-0 mt-3">
						<li><p class="mx-2 text-capitalize">follow us on : </p></li>
						<li class="mx-2"><a href="#" class="socialfb"><span class="fab fa fa-facebook-f"></span></a></li>
						<li class="mx-2"><a href="#" class="socialtw"><span class="fab fa fa-twitter"></span></a></li>
						<li class="mx-2"><a href="#" class="socialgp"><span class="fab fa fa-google-plus"></span></a></li>
						<li class="mx-2"><a href="#" class="socialln"><span class="fab fa fa-linkedin"></span></a></li>
						<li class="mx-2"><a href="#" class="socialyh"><span class="fab fa fa-yahoo"></span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- //copyright -->
</body>
<script>
	function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
	}
	document.getElementById("defaultOpen").click();
</script>
<script>
	var modal = document.getElementById('myModal');
	var btn = document.getElementById("myBtn");
	var span = document.getElementsByClassName("close")[0];
	btn.onclick = function() {
    modal.style.display = "block";
	}
	span.onclick = function() {
    modal.style.display = "none";
	}
	window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
	}
</script>
<script type="text/javascript">
  function check_numeric(this){
  	alert("k")
  }
</script>
</html>

app/views/welcome/get_career.js.erb
$('<%= j render "get_career" %>').modal();